name = "agentmode-web"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_BASE_URL = "https://agentdata-backend-prod.sarthakagrawal927.workers.dev/api"
NEXT_PUBLIC_GOOGLE_CLIENT_ID = "207924374505-jql1t59hkl3rdhtcsbmsc50m6vrdi6f3.apps.googleusercontent.com"
NEXT_PUBLIC_ADMIN_EMAIL = "sarthakagrawal927@gmail.com"
NEXT_PUBLIC_ADMIN_EMAILS = "sarthakagrawal927@gmail.com"
